-- =========================================================
-- 기존 테이블 초기화
-- =========================================================
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- =========================================================
-- 테이블 및 컬럼 정의
-- =========================================================

-- 1. 회원 및 보안 도메인
CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(50),
    age_range VARCHAR2(50),
    job_type VARCHAR2(100),
    purpose_id NUMBER,

    provider VARCHAR2(50),
    provider_id VARCHAR2(255),

    is_job_recommend_enabled NUMBER(1) DEFAULT 1,

    role VARCHAR2(20) DEFAULT 'ROLE_USER',
    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    last_login_at TIMESTAMP,

    CONSTRAINT chk_members_job_recommend CHECK (is_job_recommend_enabled IN (0,1)),
    CONSTRAINT chk_members_role CHECK (role IN ('ROLE_USER','ROLE_ADMIN')),
    CONSTRAINT chk_members_status CHECK (
        status IN ('ACTIVE', 'WITHDRAWN', 'SUSPENDED', 'DORMANT')
    )
);

-- 1-2. 비밀번호 재설정 토큰
CREATE TABLE password_reset_tokens (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    token VARCHAR2(255) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,

    CONSTRAINT fk_password_reset_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);

-- 2. 웹 접근성 설정
CREATE TABLE accessibility_settings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER UNIQUE NOT NULL,

    font_size_step NUMBER DEFAULT 1,
    high_contrast_enabled NUMBER(1) DEFAULT 0,
    screen_reader_optimized NUMBER(1) DEFAULT 0,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_accessibility_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
);

-- 3. 배송지 및 주문 정보
CREATE TABLE addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,

    address_name VARCHAR2(100),
    zip_code VARCHAR2(20),
    base_address VARCHAR2(255),
    detail_address VARCHAR2(255),

    receiver_name VARCHAR2(100),
    receiver_phone VARCHAR2(50),

    is_default NUMBER(1) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_addresses_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
);

-- 4-1. 카테고리 (대/중/소 계층: parent_id 자기참조)
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    parent_id NUMBER,

    name VARCHAR2(100),

    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id)
        REFERENCES categories(id),

    CONSTRAINT chk_categories_status CHECK (
        status IN ('ACTIVE', 'DELETED')
    )
);

-- 4. 상품 및 메타 데이터
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id NUMBER,

    name VARCHAR2(255) NOT NULL,
    price NUMBER NOT NULL,
    discount_rate NUMBER DEFAULT 0 NOT NULL,
    delivery_fee NUMBER NOT NULL,

    stock_quantity NUMBER DEFAULT 0,

    short_description VARCHAR2(500),
    description CLOB,

    brand VARCHAR2(100),
    origin VARCHAR2(100),

    spec_info CLOB,

    alt_text CLOB,

    weight_score NUMBER DEFAULT 0,
    sales_count NUMBER DEFAULT 0,
    average_rate NUMBER DEFAULT 0 NOT NULL,
    review_count NUMBER DEFAULT 0 NOT NULL,

    status VARCHAR2(20) DEFAULT 'PENDING',
    reject_reason VARCHAR2(500),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT chk_products_status CHECK (
        status IN (
            'PENDING',
            'APPROVED',
            'REJECTED',
            'ON_SALE',
            'DISCONTINUED',
            'SOLD_OUT',
            'VEILED',
            'WAITING',
            'DELETED'
        )
    )
);

-- 4-2. 상품 이미지
CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id NUMBER,

    image_url VARCHAR2(500),

    is_main NUMBER(1) DEFAULT 0,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
);

-- 4-3. 메타 태그
CREATE TABLE meta_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR2(100) NOT NULL,

    type VARCHAR2(30) NOT NULL,

    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT chk_meta_tags_type CHECK (
        type IN (
            'CATEGORY',
            'SEASONAL',
            'PURPOSE',
            'MERCHANDISING',
            'OCCUPATION',
            'AGE_PREFERENCE',
            'POPULARITY',
            'RELEASE_OR_UPDATE',
            'TIME_OF_DAY',
            'PRICE_RANGE'
        )
    ),

    CONSTRAINT chk_meta_tags_status CHECK (
        status IN ('ACTIVE','DELETED')
    ),
    CONSTRAINT uq_meta_tags_name_type UNIQUE (name, type)
);

-- 4-4. 상품-메타태그 매핑
CREATE TABLE product_meta_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_product_meta_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT fk_product_meta_tag
        FOREIGN KEY (meta_tag_id)
        REFERENCES meta_tags(id),

    CONSTRAINT uq_product_meta
        UNIQUE (product_id, meta_tag_id)
);

-- 4-5. 카테고리별 메타태그 템플릿 (상품 등록 콜드스타트 제안용)
CREATE TABLE category_meta_tag_templates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_cat_meta_tpl_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT fk_cat_meta_tpl_tag
        FOREIGN KEY (meta_tag_id)
        REFERENCES meta_tags(id),

    CONSTRAINT uq_cat_meta_tpl
        UNIQUE (category_id, meta_tag_id)
);

-- 4-6. 유저별 취향 가중치 프로필
CREATE TABLE member_tag_weights (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,

    profile_score NUMBER DEFAULT 0,
    weight_score NUMBER DEFAULT 0,
    effective_score NUMBER DEFAULT 0,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_member_tag_weights_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_member_tag_weights_tag
        FOREIGN KEY (meta_tag_id)
        REFERENCES meta_tags(id),

    CONSTRAINT uq_member_tag_weights
        UNIQUE (member_id, meta_tag_id)
);

-- 5. 추천 로직 및 활동 데이터
CREATE TABLE metatag_weight_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    metatag_id NUMBER NOT NULL,

    action_type VARCHAR2(30),

    applied_weight NUMBER,

    reference_id NUMBER,

    event_timestamp TIMESTAMP,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE product_weight_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,

    action_type VARCHAR2(30),

    applied_weight NUMBER,

    reference_id NUMBER,

    event_timestamp TIMESTAMP,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 5-1. 북마크
CREATE TABLE bookmarks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_bookmarks_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_bookmarks_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT uq_bookmark_member_product
        UNIQUE (member_id, product_id)
);

-- 6. 주문 및 결제
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    address_id NUMBER,

    receiver_name VARCHAR2(100),
    receiver_phone VARCHAR2(50),

    delivery_address VARCHAR2(500),

    request_message VARCHAR2(500),

    total_amount NUMBER NOT NULL,
    delivery_fee NUMBER NOT NULL,

    payment_method VARCHAR2(50),

    status VARCHAR2(50) DEFAULT 'PENDING',

    tracking_number VARCHAR2(100),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_orders_address
        FOREIGN KEY (address_id)
        REFERENCES addresses(id),

    CONSTRAINT chk_orders_status CHECK (
        status IN (
            'PENDING',
            'PROCESSING',
            'COMPLETED',
            'BEFORE_SHIPMENT',
            'IN_TRANSIT',
            'DELIVERED',
            'PARTIAL_CANCELLED',
            'CANCELLED',
            'PARTIAL_RETURN_REQUESTED',
            'RETURN_REQUESTED',
            'PARTIAL_RETURN_COMPLETED',
            'RETURN_COMPLETED'
        )
    ),

    CONSTRAINT chk_orders_payment_method CHECK (
        payment_method IN (
            'CASH',
            'CARD',
            'MOBILE_PAY'
        )
    )
);

-- 6-1. 주문 아이템
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id NUMBER NOT NULL,

    source VARCHAR2(20) DEFAULT 'INTERNAL' NOT NULL,

    product_id NUMBER,

    naver_product_id VARCHAR2(100),

    product_name VARCHAR2(255),

    image_url VARCHAR2(500),

    category VARCHAR2(100),

    description CLOB,

    quantity NUMBER,

    price_at_order NUMBER,

    status VARCHAR2(20) DEFAULT 'ORDERED' NOT NULL,

    cancelled_at TIMESTAMP,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_order_items_source
        CHECK (source IN ('INTERNAL','NAVER')),

    CONSTRAINT chk_order_items_status
        CHECK (
            status IN (
                'ORDERED',
                'CANCELLED',
                'RETURN_REQUESTED',
                'RETURN_COMPLETED'
            )
        )
);

-- 6-2. 결제
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id NUMBER UNIQUE NOT NULL,

    payment_key VARCHAR2(255) UNIQUE,

    payment_method VARCHAR2(100),

    amount NUMBER,

    status VARCHAR2(50),

    approved_at TIMESTAMP,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT chk_payments_method CHECK (
        payment_method IN (
            'CASH',
            'CARD',
            'MOBILE_PAY'
        )
    ),

    CONSTRAINT chk_payments_status CHECK (
        status IN (
            'PENDING',
            'PROCESSING',
            'CANCELLED',
            'COMPLETED',
            'FAILED'
        )
    )
);

-- 6-3. 장바구니
CREATE TABLE cart_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,

    source VARCHAR2(20) DEFAULT 'INTERNAL' NOT NULL,

    product_id NUMBER,

    naver_product_id VARCHAR2(100),

    product_name VARCHAR2(255),

    image_url VARCHAR2(500),

    price NUMBER,

    quantity NUMBER,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_cart_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_cart_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_cart_items_source CHECK (
        source IN ('INTERNAL','NAVER')
    )
);

-- 7. 리뷰 및 소통
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,

    product_id NUMBER,

    order_item_id NUMBER UNIQUE NOT NULL,

    rating NUMBER NOT NULL,

    content CLOB NOT NULL,

    image_url VARCHAR2(500),

    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_reviews_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT fk_reviews_order_item
        FOREIGN KEY (order_item_id)
        REFERENCES order_items(id),

    CONSTRAINT chk_reviews_status CHECK (
        status IN ('ACTIVE','HIDDEN','DELETED')
    )
);

-- 8. 검색 및 인기 검색어
CREATE TABLE search_keywords (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    keyword VARCHAR2(100) UNIQUE NOT NULL,

    search_count NUMBER DEFAULT 1 NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
);

-- 9. 고객지원 데이터
CREATE TABLE faqs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,                    
    title CLOB NOT NULL,                              
    content CLOB NOT NULL,                            
    status VARCHAR2(20) DEFAULT 'ACTIVE',            
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,       
    
    CONSTRAINT chk_faqs_status CHECK (status IN ('ACTIVE', 'DELETED'))
);

CREATE TABLE qnas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    title VARCHAR2(255),
    content CLOB,
    answer CLOB,
    status VARCHAR2(50) DEFAULT 'WAITING',
    
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,
    answered_at TIMESTAMP,                              

    CONSTRAINT fk_qnas_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT chk_qnas_status CHECK (
        status IN ('WAITING', 'ANSWERED', 'DELETED')
    )
);

-- =========================================================
-- FK 추가
-- =========================================================

ALTER TABLE members
ADD CONSTRAINT fk_members_purpose
FOREIGN KEY (purpose_id)
REFERENCES meta_tags(id);

ALTER TABLE metatag_weight_logs
ADD CONSTRAINT fk_metatag_logs_member
FOREIGN KEY (member_id)
REFERENCES members(id);

ALTER TABLE metatag_weight_logs
ADD CONSTRAINT fk_metatag_logs_tag
FOREIGN KEY (metatag_id)
REFERENCES meta_tags(id);

ALTER TABLE product_weight_logs
ADD CONSTRAINT fk_product_logs_member
FOREIGN KEY (member_id)
REFERENCES members(id);

ALTER TABLE product_weight_logs
ADD CONSTRAINT fk_product_logs_product
FOREIGN KEY (product_id)
REFERENCES products(id);

-- =========================================================
--  시퀀스 추가
-- =========================================================

CREATE SEQUENCE META_TAGS_SEQ
    START WITH 359
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- =========================================================
--  메타 태그 초기 데이터
-- =========================================================

-- ① CATEGORY 관련 태그 (id 200~310, categories.id 1~111 과 순서 대응)
--     meta_tag_id = 199 + category_id
-- [대분류] category_id=1 → meta_tags.id=200
INSERT INTO meta_tags (id, name, type, status)
VALUES (200, '건강', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=2, categories.parent_id=1 → meta_tags.id=201
INSERT INTO meta_tags (id, name, type, status)
VALUES (201, '영양제', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=3, categories.parent_id=2 → meta_tags.id=202
INSERT INTO meta_tags (id, name, type, status)
VALUES (202, '종합비타민', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=4, categories.parent_id=2 → meta_tags.id=203
INSERT INTO meta_tags (id, name, type, status)
VALUES (203, '비타민C/D', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=5, categories.parent_id=2 → meta_tags.id=204
INSERT INTO meta_tags (id, name, type, status)
VALUES (204, '오메가3', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=6, categories.parent_id=2 → meta_tags.id=205
INSERT INTO meta_tags (id, name, type, status)
VALUES (205, '유산균/프로바이오틱스', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=7, categories.parent_id=2 → meta_tags.id=206
INSERT INTO meta_tags (id, name, type, status)
VALUES (206, '루테인', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=8, categories.parent_id=2 → meta_tags.id=207
INSERT INTO meta_tags (id, name, type, status)
VALUES (207, '칼슘/마그네슘', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=9, categories.parent_id=2 → meta_tags.id=208
INSERT INTO meta_tags (id, name, type, status)
VALUES (208, '기타 영양제', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=10, categories.parent_id=1 → meta_tags.id=209
INSERT INTO meta_tags (id, name, type, status)
VALUES (209, '건강식품', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=11, categories.parent_id=10 → meta_tags.id=210
INSERT INTO meta_tags (id, name, type, status)
VALUES (210, '홍삼/인삼', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=12, categories.parent_id=10 → meta_tags.id=211
INSERT INTO meta_tags (id, name, type, status)
VALUES (211, '꿀/로열젤리', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=13, categories.parent_id=10 → meta_tags.id=212
INSERT INTO meta_tags (id, name, type, status)
VALUES (212, '단백질/보충제', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=14, categories.parent_id=10 → meta_tags.id=213
INSERT INTO meta_tags (id, name, type, status)
VALUES (213, '다이어트 식품', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=15, categories.parent_id=10 → meta_tags.id=214
INSERT INTO meta_tags (id, name, type, status)
VALUES (214, '환/분말', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=16, categories.parent_id=10 → meta_tags.id=215
INSERT INTO meta_tags (id, name, type, status)
VALUES (215, '기타 건강식품', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=17, categories.parent_id=1 → meta_tags.id=216
INSERT INTO meta_tags (id, name, type, status)
VALUES (216, '운동/케어', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=18, categories.parent_id=17 → meta_tags.id=217
INSERT INTO meta_tags (id, name, type, status)
VALUES (217, '홈트레이닝', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=19, categories.parent_id=17 → meta_tags.id=218
INSERT INTO meta_tags (id, name, type, status)
VALUES (218, '스트레칭/마사지', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=20, categories.parent_id=17 → meta_tags.id=219
INSERT INTO meta_tags (id, name, type, status)
VALUES (219, '체중계/측정', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=21, categories.parent_id=17 → meta_tags.id=220
INSERT INTO meta_tags (id, name, type, status)
VALUES (220, '보호대/밴드', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=22, categories.parent_id=1 → meta_tags.id=221
INSERT INTO meta_tags (id, name, type, status)
VALUES (221, '의료/위생용품', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=23, categories.parent_id=22 → meta_tags.id=222
INSERT INTO meta_tags (id, name, type, status)
VALUES (222, '마스크/손소독', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=24, categories.parent_id=22 → meta_tags.id=223
INSERT INTO meta_tags (id, name, type, status)
VALUES (223, '체온계/혈압계', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=25, categories.parent_id=22 → meta_tags.id=224
INSERT INTO meta_tags (id, name, type, status)
VALUES (224, '상비약 관련 용품', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=26, categories.parent_id=22 → meta_tags.id=225
INSERT INTO meta_tags (id, name, type, status)
VALUES (225, '위생용품', 'CATEGORY', 'ACTIVE');

-- [대분류] category_id=27 → meta_tags.id=226
INSERT INTO meta_tags (id, name, type, status)
VALUES (226, '교육', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=28, categories.parent_id=27 → meta_tags.id=227
INSERT INTO meta_tags (id, name, type, status)
VALUES (227, '도서', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=29, categories.parent_id=28 → meta_tags.id=228
INSERT INTO meta_tags (id, name, type, status)
VALUES (228, '자기계발', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=30, categories.parent_id=28 → meta_tags.id=229
INSERT INTO meta_tags (id, name, type, status)
VALUES (229, '경제/경영', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=31, categories.parent_id=28 → meta_tags.id=230
INSERT INTO meta_tags (id, name, type, status)
VALUES (230, '자격증/수험', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=32, categories.parent_id=28 → meta_tags.id=231
INSERT INTO meta_tags (id, name, type, status)
VALUES (231, '외국어', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=33, categories.parent_id=28 → meta_tags.id=232
INSERT INTO meta_tags (id, name, type, status)
VALUES (232, '아동/청소년', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=34, categories.parent_id=28 → meta_tags.id=233
INSERT INTO meta_tags (id, name, type, status)
VALUES (233, '기타 도서', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=35, categories.parent_id=27 → meta_tags.id=234
INSERT INTO meta_tags (id, name, type, status)
VALUES (234, '문구/오피스', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=36, categories.parent_id=35 → meta_tags.id=235
INSERT INTO meta_tags (id, name, type, status)
VALUES (235, '필기구', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=37, categories.parent_id=35 → meta_tags.id=236
INSERT INTO meta_tags (id, name, type, status)
VALUES (236, '노트/다이어리', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=38, categories.parent_id=35 → meta_tags.id=237
INSERT INTO meta_tags (id, name, type, status)
VALUES (237, '데스크 정리', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=39, categories.parent_id=35 → meta_tags.id=238
INSERT INTO meta_tags (id, name, type, status)
VALUES (238, '프린터/용지 소모품', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=40, categories.parent_id=27 → meta_tags.id=239
INSERT INTO meta_tags (id, name, type, status)
VALUES (239, '학습기기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=41, categories.parent_id=40 → meta_tags.id=240
INSERT INTO meta_tags (id, name, type, status)
VALUES (240, '전자사전/학습기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=42, categories.parent_id=40 → meta_tags.id=241
INSERT INTO meta_tags (id, name, type, status)
VALUES (241, '태블릿 액세서리', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=43, categories.parent_id=40 → meta_tags.id=242
INSERT INTO meta_tags (id, name, type, status)
VALUES (242, '스탠드/조명', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=44, categories.parent_id=27 → meta_tags.id=243
INSERT INTO meta_tags (id, name, type, status)
VALUES (243, '온라인/강의용품', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=45, categories.parent_id=44 → meta_tags.id=244
INSERT INTO meta_tags (id, name, type, status)
VALUES (244, '이어폰/헤드셋', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=46, categories.parent_id=44 → meta_tags.id=245
INSERT INTO meta_tags (id, name, type, status)
VALUES (245, '웹캠/마이크', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=47, categories.parent_id=44 → meta_tags.id=246
INSERT INTO meta_tags (id, name, type, status)
VALUES (246, '노트북 거치대', 'CATEGORY', 'ACTIVE');

-- [대분류] category_id=48 → meta_tags.id=247
INSERT INTO meta_tags (id, name, type, status)
VALUES (247, '여행', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=49, categories.parent_id=48 → meta_tags.id=248
INSERT INTO meta_tags (id, name, type, status)
VALUES (248, '여행가방', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=50, categories.parent_id=49 → meta_tags.id=249
INSERT INTO meta_tags (id, name, type, status)
VALUES (249, '캐리어', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=51, categories.parent_id=49 → meta_tags.id=250
INSERT INTO meta_tags (id, name, type, status)
VALUES (250, '백팩', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=52, categories.parent_id=49 → meta_tags.id=251
INSERT INTO meta_tags (id, name, type, status)
VALUES (251, '크로스백/숄더', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=53, categories.parent_id=49 → meta_tags.id=252
INSERT INTO meta_tags (id, name, type, status)
VALUES (252, '파우치/정리백', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=54, categories.parent_id=48 → meta_tags.id=253
INSERT INTO meta_tags (id, name, type, status)
VALUES (253, '여행용품', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=55, categories.parent_id=54 → meta_tags.id=254
INSERT INTO meta_tags (id, name, type, status)
VALUES (254, '목베개/아이마스크', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=56, categories.parent_id=54 → meta_tags.id=255
INSERT INTO meta_tags (id, name, type, status)
VALUES (255, '어댑터/충전기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=57, categories.parent_id=54 → meta_tags.id=256
INSERT INTO meta_tags (id, name, type, status)
VALUES (256, '세면도구 세트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=58, categories.parent_id=54 → meta_tags.id=257
INSERT INTO meta_tags (id, name, type, status)
VALUES (257, '여행용 수납', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=59, categories.parent_id=48 → meta_tags.id=258
INSERT INTO meta_tags (id, name, type, status)
VALUES (258, '아웃도어', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=60, categories.parent_id=59 → meta_tags.id=259
INSERT INTO meta_tags (id, name, type, status)
VALUES (259, '캠핑/피크닉', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=61, categories.parent_id=59 → meta_tags.id=260
INSERT INTO meta_tags (id, name, type, status)
VALUES (260, '보온/보냉', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=62, categories.parent_id=59 → meta_tags.id=261
INSERT INTO meta_tags (id, name, type, status)
VALUES (261, '우산/우비', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=63, categories.parent_id=59 → meta_tags.id=262
INSERT INTO meta_tags (id, name, type, status)
VALUES (262, '모자/액세서리', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=64, categories.parent_id=48 → meta_tags.id=263
INSERT INTO meta_tags (id, name, type, status)
VALUES (263, '여행편의', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=65, categories.parent_id=64 → meta_tags.id=264
INSERT INTO meta_tags (id, name, type, status)
VALUES (264, '여권/카드 지갑', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=66, categories.parent_id=64 → meta_tags.id=265
INSERT INTO meta_tags (id, name, type, status)
VALUES (265, '네임택/자물쇠', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=67, categories.parent_id=64 → meta_tags.id=266
INSERT INTO meta_tags (id, name, type, status)
VALUES (266, '기타 여행 잡화', 'CATEGORY', 'ACTIVE');

-- [대분류] category_id=68 → meta_tags.id=267
INSERT INTO meta_tags (id, name, type, status)
VALUES (267, '선물', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=69, categories.parent_id=68 → meta_tags.id=268
INSERT INTO meta_tags (id, name, type, status)
VALUES (268, '식품 선물세트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=70, categories.parent_id=69 → meta_tags.id=269
INSERT INTO meta_tags (id, name, type, status)
VALUES (269, '건강식품 세트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=71, categories.parent_id=69 → meta_tags.id=270
INSERT INTO meta_tags (id, name, type, status)
VALUES (270, '차/커피 세트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=72, categories.parent_id=69 → meta_tags.id=271
INSERT INTO meta_tags (id, name, type, status)
VALUES (271, '과자/디저트 세트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=73, categories.parent_id=69 → meta_tags.id=272
INSERT INTO meta_tags (id, name, type, status)
VALUES (272, '축산/수산 세트', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=74, categories.parent_id=68 → meta_tags.id=273
INSERT INTO meta_tags (id, name, type, status)
VALUES (273, '생활 선물', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=75, categories.parent_id=74 → meta_tags.id=274
INSERT INTO meta_tags (id, name, type, status)
VALUES (274, '수건/침구', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=76, categories.parent_id=74 → meta_tags.id=275
INSERT INTO meta_tags (id, name, type, status)
VALUES (275, '향초/디퓨저', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=77, categories.parent_id=74 → meta_tags.id=276
INSERT INTO meta_tags (id, name, type, status)
VALUES (276, '키친/테이블웨어', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=78, categories.parent_id=74 → meta_tags.id=277
INSERT INTO meta_tags (id, name, type, status)
VALUES (277, '생활잡화 세트', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=79, categories.parent_id=68 → meta_tags.id=278
INSERT INTO meta_tags (id, name, type, status)
VALUES (278, '디지털/가전 선물', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=80, categories.parent_id=79 → meta_tags.id=279
INSERT INTO meta_tags (id, name, type, status)
VALUES (279, '소형가전', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=81, categories.parent_id=79 → meta_tags.id=280
INSERT INTO meta_tags (id, name, type, status)
VALUES (280, '음향기기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=82, categories.parent_id=79 → meta_tags.id=281
INSERT INTO meta_tags (id, name, type, status)
VALUES (281, '스마트 액세서리', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=83, categories.parent_id=68 → meta_tags.id=282
INSERT INTO meta_tags (id, name, type, status)
VALUES (282, '기념일/시즌', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=84, categories.parent_id=83 → meta_tags.id=283
INSERT INTO meta_tags (id, name, type, status)
VALUES (283, '생일/축하', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=85, categories.parent_id=83 → meta_tags.id=284
INSERT INTO meta_tags (id, name, type, status)
VALUES (284, '명절 세트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=86, categories.parent_id=83 → meta_tags.id=285
INSERT INTO meta_tags (id, name, type, status)
VALUES (285, '답례품', 'CATEGORY', 'ACTIVE');

-- [대분류] category_id=87 → meta_tags.id=286
INSERT INTO meta_tags (id, name, type, status)
VALUES (286, '가전', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=88, categories.parent_id=87 → meta_tags.id=287
INSERT INTO meta_tags (id, name, type, status)
VALUES (287, '생활가전', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=89, categories.parent_id=88 → meta_tags.id=288
INSERT INTO meta_tags (id, name, type, status)
VALUES (288, '청소기/로봇청소기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=90, categories.parent_id=88 → meta_tags.id=289
INSERT INTO meta_tags (id, name, type, status)
VALUES (289, '공기청정기/가습기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=91, categories.parent_id=88 → meta_tags.id=290
INSERT INTO meta_tags (id, name, type, status)
VALUES (290, '선풍기/히터', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=92, categories.parent_id=88 → meta_tags.id=291
INSERT INTO meta_tags (id, name, type, status)
VALUES (291, '다리미/스팀', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=93, categories.parent_id=87 → meta_tags.id=292
INSERT INTO meta_tags (id, name, type, status)
VALUES (292, '주방가전', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=94, categories.parent_id=93 → meta_tags.id=293
INSERT INTO meta_tags (id, name, type, status)
VALUES (293, '전기밥솥/쿠커', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=95, categories.parent_id=93 → meta_tags.id=294
INSERT INTO meta_tags (id, name, type, status)
VALUES (294, '전자레인지/오븐', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=96, categories.parent_id=93 → meta_tags.id=295
INSERT INTO meta_tags (id, name, type, status)
VALUES (295, '커피머신/전기포트', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=97, categories.parent_id=93 → meta_tags.id=296
INSERT INTO meta_tags (id, name, type, status)
VALUES (296, '믹서/블렌더', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=98, categories.parent_id=93 → meta_tags.id=297
INSERT INTO meta_tags (id, name, type, status)
VALUES (297, '식기세척/건조', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=99, categories.parent_id=87 → meta_tags.id=298
INSERT INTO meta_tags (id, name, type, status)
VALUES (298, '디지털', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=100, categories.parent_id=99 → meta_tags.id=299
INSERT INTO meta_tags (id, name, type, status)
VALUES (299, 'TV/모니터', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=101, categories.parent_id=99 → meta_tags.id=300
INSERT INTO meta_tags (id, name, type, status)
VALUES (300, '노트북/PC주변기기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=102, categories.parent_id=99 → meta_tags.id=301
INSERT INTO meta_tags (id, name, type, status)
VALUES (301, '태블릿/스마트폰 액세서리', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=103, categories.parent_id=99 → meta_tags.id=302
INSERT INTO meta_tags (id, name, type, status)
VALUES (302, '음향(스피커/이어폰)', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=104, categories.parent_id=87 → meta_tags.id=303
INSERT INTO meta_tags (id, name, type, status)
VALUES (303, '계절가전', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=105, categories.parent_id=104 → meta_tags.id=304
INSERT INTO meta_tags (id, name, type, status)
VALUES (304, '에어컨/선풍기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=106, categories.parent_id=104 → meta_tags.id=305
INSERT INTO meta_tags (id, name, type, status)
VALUES (305, '난방기기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=107, categories.parent_id=104 → meta_tags.id=306
INSERT INTO meta_tags (id, name, type, status)
VALUES (306, '제습기/가습기', 'CATEGORY', 'ACTIVE');

-- [중분류] category_id=108, categories.parent_id=87 → meta_tags.id=307
INSERT INTO meta_tags (id, name, type, status)
VALUES (307, '이미용가전', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=109, categories.parent_id=108 → meta_tags.id=308
INSERT INTO meta_tags (id, name, type, status)
VALUES (308, '드라이기/고데기', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=110, categories.parent_id=108 → meta_tags.id=309
INSERT INTO meta_tags (id, name, type, status)
VALUES (309, '면도기/제모', 'CATEGORY', 'ACTIVE');

-- [소분류] category_id=111, categories.parent_id=108 → meta_tags.id=310
INSERT INTO meta_tags (id, name, type, status)
VALUES (310, '피부관리기기', 'CATEGORY', 'ACTIVE');

-- ② PURPOSE 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (311, '나를 위한 구매', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (312, '선물용', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (313, '가족/아이', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (314, '업무/직장', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (315, '취미/여가', 'PURPOSE', 'ACTIVE');

-- ③ MERCHANDISING 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (316, '가성비', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (317, '고품질', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (318, '실용적', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (319, '트렌디', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (320, '친환경', 'MERCHANDISING', 'ACTIVE');

-- ④ OCCUPATION(JOB_TYPE/직종) 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (321, '사무', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (322, '영업', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (323, '현장', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (324, '의료', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (325, '교육', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (326, '기타', 'OCCUPATION', 'ACTIVE');

-- ⑤ 연령대(AGE_PREFERENCE) 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (327, '영유아', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (328, '10대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (329, '20대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (330, '30대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (331, '40대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (332, '50대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (333, '60대 이상', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (334, '전연령', 'AGE_PREFERENCE', 'ACTIVE');

-- ⑥ SEASONAL(계절 별) 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (335, '초봄', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (336, '봄', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (337, '여름', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (338, '초가을', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (339, '가을', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (340, '초겨울', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (341, '겨울', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (342, '장마', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (343, '연말', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (344, '연초', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (345, '명절', 'SEASONAL', 'ACTIVE');

-- ⑦ POPULARITY 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (346, '인기 상품', 'POPULARITY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (347, '스테디셀러', 'POPULARITY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (348, '주목 상품', 'POPULARITY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (349, '특가 세일', 'POPULARITY', 'ACTIVE');

-- ⑧ RELEASE_OR_UPDATE 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (350, '신상품', 'RELEASE_OR_UPDATE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (351, '업데이트', 'RELEASE_OR_UPDATE', 'ACTIVE');

-- ⑨ TIME_OF_DAY(구매 시간대) 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (352, '오전', 'TIME_OF_DAY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (353, '오후', 'TIME_OF_DAY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (354, '저녁', 'TIME_OF_DAY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (355, '심야', 'TIME_OF_DAY', 'ACTIVE');

-- ⑩ PRICE_RANGE(가격대) 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (356, '저가', 'PRICE_RANGE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (357, '중가', 'PRICE_RANGE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (358, '고가', 'PRICE_RANGE', 'ACTIVE');

-- =========================================================
-- CATEGORY 테이블 초기 데이터 (대분류 → 중분류 → 소분류 DFS 순서)
-- id 1~111 / meta_tags CATEGORY id = 199 + category_id (200~310)
-- =========================================================

-- [대분류] 건강
INSERT INTO categories(id, parent_id, name)
VALUES (1, NULL, '건강');

--   [중분류] 영양제
INSERT INTO categories(id, parent_id, name)
VALUES (2, 1, '영양제');

--     [소분류] 종합비타민
INSERT INTO categories(id, parent_id, name)
VALUES (3, 2, '종합비타민');

--     [소분류] 비타민C/D
INSERT INTO categories(id, parent_id, name)
VALUES (4, 2, '비타민C/D');

--     [소분류] 오메가3
INSERT INTO categories(id, parent_id, name)
VALUES (5, 2, '오메가3');

--     [소분류] 유산균/프로바이오틱스
INSERT INTO categories(id, parent_id, name)
VALUES (6, 2, '유산균/프로바이오틱스');

--     [소분류] 루테인
INSERT INTO categories(id, parent_id, name)
VALUES (7, 2, '루테인');

--     [소분류] 칼슘/마그네슘
INSERT INTO categories(id, parent_id, name)
VALUES (8, 2, '칼슘/마그네슘');

--     [소분류] 기타 영양제
INSERT INTO categories(id, parent_id, name)
VALUES (9, 2, '기타 영양제');

--   [중분류] 건강식품
INSERT INTO categories(id, parent_id, name)
VALUES (10, 1, '건강식품');

--     [소분류] 홍삼/인삼
INSERT INTO categories(id, parent_id, name)
VALUES (11, 10, '홍삼/인삼');

--     [소분류] 꿀/로열젤리
INSERT INTO categories(id, parent_id, name)
VALUES (12, 10, '꿀/로열젤리');

--     [소분류] 단백질/보충제
INSERT INTO categories(id, parent_id, name)
VALUES (13, 10, '단백질/보충제');

--     [소분류] 다이어트 식품
INSERT INTO categories(id, parent_id, name)
VALUES (14, 10, '다이어트 식품');

--     [소분류] 환/분말
INSERT INTO categories(id, parent_id, name)
VALUES (15, 10, '환/분말');

--     [소분류] 기타 건강식품
INSERT INTO categories(id, parent_id, name)
VALUES (16, 10, '기타 건강식품');

--   [중분류] 운동/케어
INSERT INTO categories(id, parent_id, name)
VALUES (17, 1, '운동/케어');

--     [소분류] 홈트레이닝
INSERT INTO categories(id, parent_id, name)
VALUES (18, 17, '홈트레이닝');

--     [소분류] 스트레칭/마사지
INSERT INTO categories(id, parent_id, name)
VALUES (19, 17, '스트레칭/마사지');

--     [소분류] 체중계/측정
INSERT INTO categories(id, parent_id, name)
VALUES (20, 17, '체중계/측정');

--     [소분류] 보호대/밴드
INSERT INTO categories(id, parent_id, name)
VALUES (21, 17, '보호대/밴드');

--   [중분류] 의료/위생용품
INSERT INTO categories(id, parent_id, name)
VALUES (22, 1, '의료/위생용품');

--     [소분류] 마스크/손소독
INSERT INTO categories(id, parent_id, name)
VALUES (23, 22, '마스크/손소독');

--     [소분류] 체온계/혈압계
INSERT INTO categories(id, parent_id, name)
VALUES (24, 22, '체온계/혈압계');

--     [소분류] 상비약 관련 용품
INSERT INTO categories(id, parent_id, name)
VALUES (25, 22, '상비약 관련 용품');

--     [소분류] 위생용품
INSERT INTO categories(id, parent_id, name)
VALUES (26, 22, '위생용품');

-- [대분류] 교육
INSERT INTO categories(id, parent_id, name)
VALUES (27, NULL, '교육');

--   [중분류] 도서
INSERT INTO categories(id, parent_id, name)
VALUES (28, 27, '도서');

--     [소분류] 자기계발
INSERT INTO categories(id, parent_id, name)
VALUES (29, 28, '자기계발');

--     [소분류] 경제/경영
INSERT INTO categories(id, parent_id, name)
VALUES (30, 28, '경제/경영');

--     [소분류] 자격증/수험
INSERT INTO categories(id, parent_id, name)
VALUES (31, 28, '자격증/수험');

--     [소분류] 외국어
INSERT INTO categories(id, parent_id, name)
VALUES (32, 28, '외국어');

--     [소분류] 아동/청소년
INSERT INTO categories(id, parent_id, name)
VALUES (33, 28, '아동/청소년');

--     [소분류] 기타 도서
INSERT INTO categories(id, parent_id, name)
VALUES (34, 28, '기타 도서');

--   [중분류] 문구/오피스
INSERT INTO categories(id, parent_id, name)
VALUES (35, 27, '문구/오피스');

--     [소분류] 필기구
INSERT INTO categories(id, parent_id, name)
VALUES (36, 35, '필기구');

--     [소분류] 노트/다이어리
INSERT INTO categories(id, parent_id, name)
VALUES (37, 35, '노트/다이어리');

--     [소분류] 데스크 정리
INSERT INTO categories(id, parent_id, name)
VALUES (38, 35, '데스크 정리');

--     [소분류] 프린터/용지 소모품
INSERT INTO categories(id, parent_id, name)
VALUES (39, 35, '프린터/용지 소모품');

--   [중분류] 학습기기
INSERT INTO categories(id, parent_id, name)
VALUES (40, 27, '학습기기');

--     [소분류] 전자사전/학습기
INSERT INTO categories(id, parent_id, name)
VALUES (41, 40, '전자사전/학습기');

--     [소분류] 태블릿 액세서리
INSERT INTO categories(id, parent_id, name)
VALUES (42, 40, '태블릿 액세서리');

--     [소분류] 스탠드/조명
INSERT INTO categories(id, parent_id, name)
VALUES (43, 40, '스탠드/조명');

--   [중분류] 온라인/강의용품
INSERT INTO categories(id, parent_id, name)
VALUES (44, 27, '온라인/강의용품');

--     [소분류] 이어폰/헤드셋
INSERT INTO categories(id, parent_id, name)
VALUES (45, 44, '이어폰/헤드셋');

--     [소분류] 웹캠/마이크
INSERT INTO categories(id, parent_id, name)
VALUES (46, 44, '웹캠/마이크');

--     [소분류] 노트북 거치대
INSERT INTO categories(id, parent_id, name)
VALUES (47, 44, '노트북 거치대');

-- [대분류] 여행
INSERT INTO categories(id, parent_id, name)
VALUES (48, NULL, '여행');

--   [중분류] 여행가방
INSERT INTO categories(id, parent_id, name)
VALUES (49, 48, '여행가방');

--     [소분류] 캐리어
INSERT INTO categories(id, parent_id, name)
VALUES (50, 49, '캐리어');

--     [소분류] 백팩
INSERT INTO categories(id, parent_id, name)
VALUES (51, 49, '백팩');

--     [소분류] 크로스백/숄더
INSERT INTO categories(id, parent_id, name)
VALUES (52, 49, '크로스백/숄더');

--     [소분류] 파우치/정리백
INSERT INTO categories(id, parent_id, name)
VALUES (53, 49, '파우치/정리백');

--   [중분류] 여행용품
INSERT INTO categories(id, parent_id, name)
VALUES (54, 48, '여행용품');

--     [소분류] 목베개/아이마스크
INSERT INTO categories(id, parent_id, name)
VALUES (55, 54, '목베개/아이마스크');

--     [소분류] 어댑터/충전기
INSERT INTO categories(id, parent_id, name)
VALUES (56, 54, '어댑터/충전기');

--     [소분류] 세면도구 세트
INSERT INTO categories(id, parent_id, name)
VALUES (57, 54, '세면도구 세트');

--     [소분류] 여행용 수납
INSERT INTO categories(id, parent_id, name)
VALUES (58, 54, '여행용 수납');

--   [중분류] 아웃도어
INSERT INTO categories(id, parent_id, name)
VALUES (59, 48, '아웃도어');

--     [소분류] 캠핑/피크닉
INSERT INTO categories(id, parent_id, name)
VALUES (60, 59, '캠핑/피크닉');

--     [소분류] 보온/보냉
INSERT INTO categories(id, parent_id, name)
VALUES (61, 59, '보온/보냉');

--     [소분류] 우산/우비
INSERT INTO categories(id, parent_id, name)
VALUES (62, 59, '우산/우비');

--     [소분류] 모자/액세서리
INSERT INTO categories(id, parent_id, name)
VALUES (63, 59, '모자/액세서리');

--   [중분류] 여행편의
INSERT INTO categories(id, parent_id, name)
VALUES (64, 48, '여행편의');

--     [소분류] 여권/카드 지갑
INSERT INTO categories(id, parent_id, name)
VALUES (65, 64, '여권/카드 지갑');

--     [소분류] 네임택/자물쇠
INSERT INTO categories(id, parent_id, name)
VALUES (66, 64, '네임택/자물쇠');

--     [소분류] 기타 여행 잡화
INSERT INTO categories(id, parent_id, name)
VALUES (67, 64, '기타 여행 잡화');

-- [대분류] 선물
INSERT INTO categories(id, parent_id, name)
VALUES (68, NULL, '선물');

--   [중분류] 식품 선물세트
INSERT INTO categories(id, parent_id, name)
VALUES (69, 68, '식품 선물세트');

--     [소분류] 건강식품 세트
INSERT INTO categories(id, parent_id, name)
VALUES (70, 69, '건강식품 세트');

--     [소분류] 차/커피 세트
INSERT INTO categories(id, parent_id, name)
VALUES (71, 69, '차/커피 세트');

--     [소분류] 과자/디저트 세트
INSERT INTO categories(id, parent_id, name)
VALUES (72, 69, '과자/디저트 세트');

--     [소분류] 축산/수산 세트
INSERT INTO categories(id, parent_id, name)
VALUES (73, 69, '축산/수산 세트');

--   [중분류] 생활 선물
INSERT INTO categories(id, parent_id, name)
VALUES (74, 68, '생활 선물');

--     [소분류] 수건/침구
INSERT INTO categories(id, parent_id, name)
VALUES (75, 74, '수건/침구');

--     [소분류] 향초/디퓨저
INSERT INTO categories(id, parent_id, name)
VALUES (76, 74, '향초/디퓨저');

--     [소분류] 키친/테이블웨어
INSERT INTO categories(id, parent_id, name)
VALUES (77, 74, '키친/테이블웨어');

--     [소분류] 생활잡화 세트
INSERT INTO categories(id, parent_id, name)
VALUES (78, 74, '생활잡화 세트');

--   [중분류] 디지털/가전 선물
INSERT INTO categories(id, parent_id, name)
VALUES (79, 68, '디지털/가전 선물');

--     [소분류] 소형가전
INSERT INTO categories(id, parent_id, name)
VALUES (80, 79, '소형가전');

--     [소분류] 음향기기
INSERT INTO categories(id, parent_id, name)
VALUES (81, 79, '음향기기');

--     [소분류] 스마트 액세서리
INSERT INTO categories(id, parent_id, name)
VALUES (82, 79, '스마트 액세서리');

--   [중분류] 기념일/시즌
INSERT INTO categories(id, parent_id, name)
VALUES (83, 68, '기념일/시즌');

--     [소분류] 생일/축하
INSERT INTO categories(id, parent_id, name)
VALUES (84, 83, '생일/축하');

--     [소분류] 명절 세트
INSERT INTO categories(id, parent_id, name)
VALUES (85, 83, '명절 세트');

--     [소분류] 답례품
INSERT INTO categories(id, parent_id, name)
VALUES (86, 83, '답례품');

-- [대분류] 가전
INSERT INTO categories(id, parent_id, name)
VALUES (87, NULL, '가전');

--   [중분류] 생활가전
INSERT INTO categories(id, parent_id, name)
VALUES (88, 87, '생활가전');

--     [소분류] 청소기/로봇청소기
INSERT INTO categories(id, parent_id, name)
VALUES (89, 88, '청소기/로봇청소기');

--     [소분류] 공기청정기/가습기
INSERT INTO categories(id, parent_id, name)
VALUES (90, 88, '공기청정기/가습기');

--     [소분류] 선풍기/히터
INSERT INTO categories(id, parent_id, name)
VALUES (91, 88, '선풍기/히터');

--     [소분류] 다리미/스팀
INSERT INTO categories(id, parent_id, name)
VALUES (92, 88, '다리미/스팀');

--   [중분류] 주방가전
INSERT INTO categories(id, parent_id, name)
VALUES (93, 87, '주방가전');

--     [소분류] 전기밥솥/쿠커
INSERT INTO categories(id, parent_id, name)
VALUES (94, 93, '전기밥솥/쿠커');

--     [소분류] 전자레인지/오븐
INSERT INTO categories(id, parent_id, name)
VALUES (95, 93, '전자레인지/오븐');

--     [소분류] 커피머신/전기포트
INSERT INTO categories(id, parent_id, name)
VALUES (96, 93, '커피머신/전기포트');

--     [소분류] 믹서/블렌더
INSERT INTO categories(id, parent_id, name)
VALUES (97, 93, '믹서/블렌더');

--     [소분류] 식기세척/건조
INSERT INTO categories(id, parent_id, name)
VALUES (98, 93, '식기세척/건조');

--   [중분류] 디지털
INSERT INTO categories(id, parent_id, name)
VALUES (99, 87, '디지털');

--     [소분류] TV/모니터
INSERT INTO categories(id, parent_id, name)
VALUES (100, 99, 'TV/모니터');

--     [소분류] 노트북/PC주변기기
INSERT INTO categories(id, parent_id, name)
VALUES (101, 99, '노트북/PC주변기기');

--     [소분류] 태블릿/스마트폰 액세서리
INSERT INTO categories(id, parent_id, name)
VALUES (102, 99, '태블릿/스마트폰 액세서리');

--     [소분류] 음향(스피커/이어폰)
INSERT INTO categories(id, parent_id, name)
VALUES (103, 99, '음향(스피커/이어폰)');

--   [중분류] 계절가전
INSERT INTO categories(id, parent_id, name)
VALUES (104, 87, '계절가전');

--     [소분류] 에어컨/선풍기
INSERT INTO categories(id, parent_id, name)
VALUES (105, 104, '에어컨/선풍기');

--     [소분류] 난방기기
INSERT INTO categories(id, parent_id, name)
VALUES (106, 104, '난방기기');

--     [소분류] 제습기/가습기
INSERT INTO categories(id, parent_id, name)
VALUES (107, 104, '제습기/가습기');

--   [중분류] 이미용가전
INSERT INTO categories(id, parent_id, name)
VALUES (108, 87, '이미용가전');

--     [소분류] 드라이기/고데기
INSERT INTO categories(id, parent_id, name)
VALUES (109, 108, '드라이기/고데기');

--     [소분류] 면도기/제모
INSERT INTO categories(id, parent_id, name)
VALUES (110, 108, '면도기/제모');

--     [소분류] 피부관리기기
INSERT INTO categories(id, parent_id, name)
VALUES (111, 108, '피부관리기기');

ALTER TABLE categories MODIFY (
  id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)
);

-- 메타태그 IDENTITY/시퀀스 동기화 (수동 ID 삽입 이후)
ALTER TABLE meta_tags MODIFY (
  id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)
);

COMMIT;
